### PR TITLE
Fix strictFunctionTypes error

### LINKED ISSUE #39: "strictFunctionTypes" compiler option leads to error
This is a continuation from this comment from https://github.com/supermacro/neverthrow/issues/36#issuecomment-631706079

Looks like the `strictFunctionTypes` compiler option leads to a rather cumbersome type error which looks to have merit. 

This [SO](https://stackoverflow.com/questions/51767338/what-is-the-benefit-of-using-strictfunctiontypes-in-typescript) thread and the [official docs on the subject](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html) are great resources for explaining what `strictFunctionTypes` is, but I personally have not sat down to really think this through to know what the implications for `neverthrow` are. 

Below is a demonstration where there are type errors when the `strictFunctionTypes` is turned on.

Code example: https://repl.it/repls/SparseSaltyPdf

Screenshot:

Screen Shot 2020-05-21 at 10 16 01 AM

### PR DESCRIPTION
**Pull request by paduc**
Relates to #39 : will remove the compiler error when using `strictFunctionTypes` but might not solve the fundamental type checking issue.

### CODE REVIEW

File: src/result-async.ts [hunk 1]
```diff
@@ -30,8 +30,8 @@ export class ResultAsync<T, E> {
     return new ResultAsync(newPromise)
   }
 
-  map = <A>(f: (t: T) => A | Promise<A>) =>
-    new ResultAsync(
+  map<A>(f: (t: T) => A | Promise<A>) {
```
Comment (supermacro) [inline src/result-async.ts:33]: While we're at it, would you be able to also specify the return type for all of these methods?

Comment (paduc) [reply src/result-async.ts:33]: I believe I removed them at your request because the compiler could extrapolate them. Maybe I misunderstood.

Is it necessary if the compiler is capable of extrapolating them ?

**Comment by supermacro** [comment]
I'm starting to believe that there's a problem with my configuration of travis ci 🤔 ... for now please run the checks locally.

**Comment by paduc** [comment]
Should we change the `tsconfig.json` to add `strict` to catch this type of error at the `npm run typecheck` phase ?

File: src/result-async.ts (hunk 1 above)
Comment (supermacro) [reply src/result-async.ts:33]: Hmm I don't believe I requested to remove the return type. If I did I apologise.

like you mentioned, It's not necessary as the compiler can infer the return type. But by having an explicit type annotation, you create a contract. And in the future if another person comes in and changes this code, then it must adhere to the contract! And we can tell if the change still adheres to the contract or not via typechecking.

**Comment by supermacro** [comment]
> Should we change the tsconfig.json to add strict to catch this type of error at the npm run typecheck phase ?

Not until it's deemed that the flag should always be set in a TS project, based on the ongoing discussion on #39

File: src/result-async.ts (hunk 1 above)
Comment (paduc) [reply src/result-async.ts]: Ok thanks for clearing this up. I just pushed a commit to add the return types back.
